POST http://localhost:8080/article
Content-Type: application/x-www-form-urlencoded;charset=utf-8

title=tytul&content=content&firstName=Adam&lastName=Mickiewicz

###
POST http://localhost:8080/author
Content-Type: application/x-www-form-urlencoded;charset=utf-8

firstName=Adam&lastName=Mickiewicz&name=nazwaKtegorii&description=opis